import pyttsx3
import speech_recognition as sr

engine = pyttsx3.init()
engine.say("hallo ")
engine.runAndWait()
engine = pyttsx3.init()
engine.say("saya adalah alat yang dibuat untuk membantu latihan kemandirian di rumah")
engine.runAndWait()
engine = pyttsx3.init()
engine.say("gunawan ayo mandi")
engine.runAndWait()
engine = pyttsx3.init()
engine.say("ayo lepas baju, baju nya ditarik keatas")
engine.runAndWait()
engine = pyttsx3.init()
engine.say("ayo lepas celana")
engine = pyttsx3.init()
engine.say("celana di tarik ke bawah, dan angkat kaki nya")
engine = pyttsx3.init()
engine.say("ambil air, siram badan")
engine = pyttsx3.init()
engine.say("siram sekali lagi")
engine = pyttsx3.init()
engine.say("siram lagi")
engine = pyttsx3.init()
engine.say("ambil sabun")
engine = pyttsx3.init()
engine.say("ratakan sabun gosok ke badan")
engine = pyttsx3.init()
engine.say("ambil air, siram ke badan")
engine.say("siram sekali lagi")
engine = pyttsx3.init()
engine.say("siram lagi")
engine = pyttsx3.init()
engine.say("siram lagi")
engine = pyttsx3.init()
engine.say("ambil handuk, lap badan nya")
engine = pyttsx3.init()
engine.say("ayo keluar, sudah selesai")

engine.runAndWait()