nama=(input ("siapa nama mu?"))
umur=(input("berapa umur mu?"))
name = " gunawan, selamat datang "
print ("hello" + name + "!")
name = " bertanya apa saja tentang programing"
print ("kamu diperbolehkan" + name + "!")
name = " bertanya apa?"
print ("kamu mau" + name + "!")
nama=(input ("pernah belajar pyton sebelumnya?"))
nama=(input ("belajar dari siapa?"))
nama=(input ("sudah berapa lama belajar?"))
nama=(input ("gimana cara nya kamu belajar lewat apa? "))
nama=(input ("udah bisa belum coding sederhana?"))
nama=(input ("kamu bkin coding untuk apa ?"))
nama=(input ("seberapa kamu yakin ini bakal berhasil?"))
nama=(input ("apa planing mu selanjutnya apa yg ingin kamu realisasikan?"))
nama=(input ("apa yang masih mnjadi kesulitan mu saat ini?"))
nama=(input ("lalu apa strategi mu untuk menyelesaikannya?"))
nama=(input ("program ini printable atau digital?"))
nama=(input ("bisa mengolah data klien?"))
nama=(input ("untuk apa?"))
nama=(input ("brarti kamu juga me record data dan history performa klien day by day?"))
nama=(input ("untuk apa?"))
nama=(input ("presentase dan grafik tentang data klien perlu?"))
nama=(input ("smart finder data klien secara otomatis dan terstruktur perlu?"))
nama=(input ("lah untuk apa emang?"))
nama=(input ("berarti kamu juga butuh program analisa data dan pemecahan masalah sehingga memperoleh saran dan intuisi pemecahan masalah berdasarkan data?"))
nama=(input ("klau program sudah memberikan rekomendasi solusi trus apa selanjutnya?"))
nama=(input ("generalisasi maksudnya?"))
nama=(input ("oh jadi tools adaptasi fungsional akan muncul berdasrakan analisis data kemampuan tadi ya?"))
name = " berhasil ya project nya semangat"
print ("semoga" + name + "!")